#!/usr/bin/env bash
set -ex

export PYTHONPATH=$PYTHONPATH:/code
# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
#bash run_demo.sh "$@"
cd /code/analysis
bash pipeline_all

# The previous version of this file was commented-out and follows below:
#
# echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'run_demo'."
# 
