#!/bin/bash

# Define seeds and cloud tags
SEEDS=(1 2 42)
CLOUD_TAGS=(
    "M2e4_R10_S0_T1_B1_Res271_n2_sol0.5"
    "M2e4_R10_S0_T1_B0.01_Res271_n2_sol0.5"
    "M2e4_R10_S0_T2_B0.01_Res271_n2_sol0.5"
    "M2e4_R10_S0_T0.5_B0.01_Res271_n2_sol0.5"
)
CLOUD_TAGSB=(
    "M2e4_R10_S0_T1_B1_Res271_n2_sol0.5"
    "M2e4_R10_S0_T1_B0.01_Res271_n2_sol0.5"
)

CLOUD_TAGSC=(
    "M2e4_R10_S0_T1_B0.01_Res271_n2_sol0.5"
)

# Set default values if not set by the user
SMAO=${SMAO:-False}
TIDES=${TIDES:-False}
MULT=${MULT:-4}
NGRID=${NGRID:-1}
HM=${HM:-True}
FT=${FT:-1.0}
CO=${CO:-False}

## Common analysis tag
ANALYSIS_TAG="Tides${TIDES}_smao${SMAO}_mult${MULT}_ngrid${NGRID}_hm${HM}_ft${FT}_co${CO}.p"
#ANALYSIS_TAGB="TidesFalse_smaoFalse_mult4_ngrid1_hmTrue_ft8.0_coFalse.p"
ANALYSIS_TAGB="Tides${TIDES}_smao${SMAO}_mult${MULT}_ngrid${NGRID}_hm${HM}_ft8.0_co${CO}.p"
CODE_BASE="/home/aleksey/code/python/starforge_mult_search/"
#
# Create a logs directory
mkdir -p logs

##Run pipeline_part_1 in parallel for each seed
# for SEED in "${SEEDS[@]}"; do
#    echo "Running pipeline_part_1 for seed $SEED..."
#    $CODE_BASE/analysis/pipeline_part_1 $SEED $ANALYSIS_TAG > logs/part1_seed_${SEED}.log 2>&1 &
# done

# Run pipeline_part_1 in parallel for each seed
# for SEED in "${SEEDS[@]}"; do
#    echo "Running pipeline_part_1 for seed $SEED..."
#    $CODE_BASE/analysis/pipeline_part_1 $SEED $ANALYSIS_TAGB > logs/part1_seed_${SEED}.log 2>&1 &
# done

wait
#
## Run pipeline_part_1_non_fid in parallel for each cloud tag
#for CLOUD_TAG in "${CLOUD_TAGS[@]}"; do
#    echo "Running pipeline_part_1_non_fid for cloud $CLOUD_TAG..."
#    $CODE_BASE/analysis/pipeline_part_1_non_fid "$CLOUD_TAG" 1 $ANALYSIS_TAG > logs/part1_nonfid_${CLOUD_TAG//\//_}_1.log 2>&1 &
#done
#
#for CLOUD_TAG in "${CLOUD_TAGS[@]}"; do
#    echo "Running pipeline_part_1_non_fid for cloud $CLOUD_TAG... Seed 2"
#    $CODE_BASE/analysis/pipeline_part_1_non_fid "$CLOUD_TAG" 2 $ANALYSIS_TAG > logs/part1_nonfid_${CLOUD_TAG//\//_}_2.log 2>&1 &
#done
##
# for CLOUD_TAG in "${CLOUD_TAGSB[@]}"; do
#    echo "Running pipeline_part_1_non_fid for cloud $CLOUD_TAG... Seed 42"
#    $CODE_BASE/analysis/pipeline_part_1_non_fid "$CLOUD_TAG" 42 $ANALYSIS_TAG > logs/part1_nonfid_${CLOUD_TAG//\//_}_42.log 2>&1 &
# done

for CLOUD_TAG in "${CLOUD_TAGSC[@]}"; do
   echo "Running pipeline_part_1_non_fid for cloud $CLOUD_TAG... Seed 42"
   $CODE_BASE/analysis/pipeline_part_1_non_fid "$CLOUD_TAG" 42 $ANALYSIS_TAGB #> logs/part1_nonfid_${CLOUD_TAG//\//_}_42.log 2>&1 
done

#$CODE_BASE/analysis/pipeline_part_1_v1.2 42 $ANALYSIS_TAG > logs/part1_v1.2.log 2>&1 &
#
## Wait for all Part 1 processes to complete
#wait
##
### Proceed to figure generation
echo "All Part 1 analyses completed."
# ehco "Starting figure generation..."
#
## Run figure generation
#for SEED in "${SEEDS[@]}"; do
#    echo "Generating figures for seed $SEED with ft=8.0..."
#    python $CODE_BASE/analysis/bound_experiment.py $SEED _TidesFalse_smaoFalse_mult4_ngrid1_hmTrue_ft8.0_coFalse 8.0 > logs/figs_ft8_seed_${SEED}.log 2>&1 &
#    echo "Generating figures for seed $SEED with ft=1.0..."
#    python $CODE_BASE/analysis/bound_experiment.py $SEED _TidesFalse_smaoFalse_mult4_ngrid1_hmTrue_ft1.0_coFalse 1.0 > logs/figs_ft1_seed_${SEED}.log 2>&1 &
#done
##
#wait
#

##Have to ensure the correct path in the figure preamble...
# python $CODE_BASE/analysis/figures/figure_preamble.py $1
# cp $1 `cat figdir`
# cp config_example1 `cat figdir`
# cp config_example2 `cat figdir`
# cd `cat figdir`
# ln -s ../M2e4_R10
# ln -s ../v1.2
# mkdir logs
# #
# #
# python $CODE_BASE/analysis/figures/fig1.py example1 > logs/fig1_1.log 2>&1
# python $CODE_BASE/analysis/figures/fig1.py example2 > logs/fig1_2.log 2>&1
# echo "Figure 1 generated."

# # python $CODE_BASE/analysis/figures/Tables.py $1 > logs/tables.log 2>&1
# #echo "Tables generated."

# ##Add figure 2 back to the pipeline(!)
# #Generate static figures
# FIG_SCRIPTS=(fig2 fig3 fig4 ex_fig1 ex_fig2 ex_fig3 ex_fig4 ex_fig6 ex_fig7 fig5)
# for SCRIPT in "${FIG_SCRIPTS[@]}"; do
#    echo "Generating static figure $SCRIPT..."
#    python $CODE_BASE/analysis/figures/$SCRIPT.py $1 > logs/${SCRIPT}.log 2>&1
#    echo "Figure $SCRIPT generated."
# done

# Completion message
# echo "Pipeline execution completed."
